version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: alitheialabs/ehrs:1.2.2
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always